### ISSUE TITLE
Example/Dummy Question

### ISSUE THREAD

**Issue by Srushtika** [webvr-india/aframevr-forum#3]
## Question: 		
No output, only white screen in browser.		
		
## More Information: 		
I've written some basic code that should display "Hello-World" in bm-font. But the output is a blank white screen. I don't even see the A-Frame logo that's usually seen on the tab.	
		
## Code: 		

   <!DOCTYPE>
    <html>
    <head>
    <script type="https://aframe.io/releases/0.3.2/aframe.min.js"></script>
    <script type="https://rawgit.com/bryik/aframe-bmfont-text-component/master/dist/aframe-bmfont- text-component.min.js"></script>

    </head>
    <body>

  	<a-assets>
        
        <img src="https://img.gs/bbdkhfbzkk/stretch/https://i.imgur.com/25P1geh.png" id="grid" crossorigin="anonymous">
        
        <img id="sky" src="images/sunrise.jpg"  />
        </a-assets>

    
    <a-scene>
      <a-entity scale="5 5 5" bmfont-text="text: HELLO WORLD !; size: 1.5; height: 0.5;" position="-1 3 -7"></a-entity>

    

    <a-entity scale="4 4 4" geometry="primitive: box;" position="0 4 -10" material="color: #c5b2a0; metalness:1; roughness: 0.3; sphericalEnvMap: #sky;">
        <a-animation easing="linear" attribute="rotation" dur="10000" to="0 0 360" repeat="indefinite">
        </a-animation>
    </a-entity>
    <a-entity position="0 -10 0"
        geometry="primitive: plane; width: 10000; height: 10000;" rotation="-90 0 0"
        material="src: #grid; repeat: 10000 10000; transparent: true;metalness:0.6; roughness: 0.4; sphericalEnvMap: #sky;">
    </a-entity>
    <a-entity light="color: white; intensity: 0.5" position="-5 5 15"></a-entity>
    <a-sky src="#sky" rotation="0 -90 0"></a-sky>
    </a-scene>
    </body>
    </html>

		
## Screenshot: 		
![screen shot 2017-05-02 at 8 59 06 pm](https://cloud.githubusercontent.com/assets/5900152/25625484/426b9afc-2f7a-11e7-86ac-b0ca61f9fea5.png)

**Comment by mukeshpathak345** [comment]
No output, only white screen in browser.

**ANSWER**
Because You Are using Afreme java script not be right so please try to change your code and 
try this script:-  **<script src="https://aframe.io/releases/0.3.2/aframe.min.js"></script>**
# **CODE**
![dddd](https://cloud.githubusercontent.com/assets/11034559/26025208/ffe3f16e-37ff-11e7-9334-e329d5ffc9c6.png)

# **DISPLAY**
![ggggg](https://cloud.githubusercontent.com/assets/11034559/26025217/20e48374-3800-11e7-8e4b-0a44038759cb.png)

**Comment by Srushtika** [comment]
Awesome @mukeshpathak345 ! It was just "type"="src" in the script tag :) I had deliberately introduced this bug in order to show new volunteers an example of how we can ask questions and get them answered easily. 

Thanks for the answer, although it is solved, I will not close this issue for now (because remember? It's an example !)
