### ISSUE TITLE
How to use aframe in drupal can any one helpme

### ISSUE THREAD

**Issue by Nallamilliveerraghavareddy** [webvr-india/aframevr-forum#4]
Here I am using drupal8 and I am asking that how to create vr using aframe in my drupal instance 
1) installation of aframe is completed
2)now how to run our own code in it

**Comment by shashikanth171** [comment]
Use A-Frame module (https://www.drupal.org/project/aframe). Based on the version of Drupal you are working on, the steps to create A-Frame scenes differ. If you could let us know, what version of Drupal you are working with. I'll guide you with steps.

**Comment by Nallamilliveerraghavareddy** [comment]
But how to add the code

**Comment by Nallamilliveerraghavareddy** [comment]
Here I am using drupal8 and I am asking for how to create vr on my page

**Comment by gurumukhi** [comment]
@Nallamilliveerraghavareddy Dyvik has worked on this, but unfortunately he is quite busy these days. He will reply here as soon as he can. In the meantime you can ask your query to him directly on telegram (@dyvik), he can answer you there quicker than here until he is back in action.

**Comment by Nallamilliveerraghavareddy** [comment]
I got solution for it I will update here

**Comment by Nallamilliveerraghavareddy** [comment]
Step 1: create a article
Step2:go to description area and select source and fullhtml and then write the code their 
Step3:save and continue it will work
